name: Swift

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: xcode-select
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Build
        run: swift build -Xswiftc -warnings-as-errors
      - name: Test
        run: swift test -Xswiftc -warnings-as-errors
